/*
 * Lazy Load - jQuery plugin for lazy loading images
 *
 * Copyright (c) 2007-2013 Mika Tuupola
 *
 * Licensed under the MIT license:
 *   http://www.opensource.org/licenses/mit-license.php
 *
 * Project home:
 *   http://www.appelsiini.net/projects/lazyload
 *
 * Version:  1.8.4
 *
 */(function(e,t,n,r){var i=e(t);e.fn.lazyload=function(n){function s(){var t=0;o.each(function(){var n=e(this);if(f.skip_invisible&&!n.is(":visible"))return;if(!e.abovethetop(this,f)&&!e.leftofbegin(this,f))if(!e.belowthefold(this,f)&&!e.rightoffold(this,f))n.trigger("appear"),t=0;else if(++t>f.failure_limit)return!1})}var o=this,u,f={threshold:0,failure_limit:0,event:"scroll",effect:"show",container:t,data_attribute:"original",skip_invisible:!0,appear:null,load:null};return n&&(r!==n.failurelimit&&(n.failure_limit=n.failurelimit,delete n.failurelimit),r!==n.effectspeed&&(n.effect_speed=n.effectspeed,delete n.effectspeed),e.extend(f,n)),u=f.container===r||f.container===t?i:e(f.container),0===f.event.indexOf("scroll")&&u.bind(f.event,function(e){return s()}),this.each(function(){var t=this,n=e(t);t.loaded=!1,n.one("appear",function(){if(!this.loaded){if(f.appear){var r=o.length;f.appear.call(t,r,f)}e("<img />").bind("load",function(){n.hide().attr("src",n.data(f.data_attribute))[f.effect](f.effect_speed),t.loaded=!0;var r=e.grep(o,function(e){return!e.loaded});o=e(r);if(f.load){var i=o.length;f.load.call(t,i,f)}}).attr("src",n.data(f.data_attribute))}}),0!==f.event.indexOf("scroll")&&n.bind(f.event,function(e){t.loaded||n.trigger("appear")})}),i.bind("resize",function(e){s()}),/iphone|ipod|ipad.*os 5/gi.test(navigator.appVersion)&&i.bind("pageshow",function(t){t.originalEvent.persisted&&o.each(function(){e(this).trigger("appear")})}),e(t).load(function(){s()}),this},e.belowthefold=function(n,s){var o;return s.container===r||s.container===t?o=i.height()+i.scrollTop():o=e(s.container).offset().top+e(s.container).height(),o<=e(n).offset().top-s.threshold},e.rightoffold=function(n,s){var o;return s.container===r||s.container===t?o=i.width()+i.scrollLeft():o=e(s.container).offset().left+e(s.container).width(),o<=e(n).offset().left-s.threshold},e.abovethetop=function(n,s){var o;return s.container===r||s.container===t?o=i.scrollTop():o=e(s.container).offset().top,o>=e(n).offset().top+s.threshold+e(n).height()},e.leftofbegin=function(n,s){var o;return s.container===r||s.container===t?o=i.scrollLeft():o=e(s.container).offset().left,o>=e(n).offset().left+s.threshold+e(n).width()},e.inviewport=function(t,n){return!e.rightoffold(t,n)&&!e.leftofbegin(t,n)&&!e.belowthefold(t,n)&&!e.abovethetop(t,n)},e.extend(e.expr[":"],{"below-the-fold":function(t){return e.belowthefold(t,{threshold:0})},"above-the-top":function(t){return!e.belowthefold(t,{threshold:0})},"right-of-screen":function(t){return e.rightoffold(t,{threshold:0})},"left-of-screen":function(t){return!e.rightoffold(t,{threshold:0})},"in-viewport":function(t){return e.inviewport(t,{threshold:0})},"above-the-fold":function(t){return!e.belowthefold(t,{threshold:0})},"right-of-fold":function(t){return e.rightoffold(t,{threshold:0})},"left-of-fold":function(t){return!e.rightoffold(t,{threshold:0})}})})(jQuery,window,document);